--- 

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: books
  labels:
    app: books-svc-rs
  annotations: 
    kubernetes.io/change-cause: "version-1"
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: books-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  template:
    metadata:
      name: books
      labels: 
        app: books-svc
    spec:
      containers:
        - image: shaikkhajaibrahim/libbookssvc:1.0
          name: books-service
          resources:
            requests: 
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 250m
          envFrom:
            - configMapRef:
                name: books-config
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: books-svc
spec:
  type: NodePort
  selector:
    app: books-svc
  ports:
    - port: 80
      targetPort: 8000
