---

apiVersion: v1
kind: ConfigMap
metadata:
  name: users-db-config
  labels:
    type : config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: usersdb


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: books-db-config
  labels:
    type : config
data:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: booksdb


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  labels:
    type : config
  DATABASE_URL: "postgresql://user:password@users-db:5432/usersdb"
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: books-config
  labels:
    type : config
data:
  DATABASE_URL: "postgresql://user:password@books-db:5432/booksdb"
  SECRET_KEY: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"



