apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarystore
  annotations: 
    kubernetes.io/change-cause: "version: 1.0"
  labels: 
    env: dev
    app: libstore
spec: 
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: libstore
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: librarystore
      labels: 
        app: libstore
    spec:
      containers:
        - name: webstore
          image: shaikkhajaibrahim/libwebstore:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          env: 
            - name: REACT_APP_BACKEND_API_URL
              value: http://user-svc:80/api/v1
            - name: REACT_APP_USERS_API_URL
              value: http://user-svc:80/api/v1/users
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata: 
  name: lib-svc
spec:
  type: NodePort
  selector:
    app: libstore    
  ports:
    - port: 80
      targetPort: 3000  
