apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdatabase
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels: 
      app: user-db
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata: 
      name: userdatabase
      labels: 
        app: user-db
    spec:
      containers:
        - name: userdatabase
          image: postgres:15-alpine
          env: 
            - name: POSTGRES_USER
              value: user 
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: usersdb # Database name to be created
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 250m
              memory: 100M
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata: 
  name: userdatabase-svc
spec:
  type: NodePort
  selector:
    app: user-db     
  ports:
    - port: 5432
      targetPort: 5432
