apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dep
  annotations: 
    kubernetes.io/change-cause: "version: v1.0"
  labels: 
    env: dev
    app: user-service
spec: 
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: user-svc-dep # Ensure this matches the labels in the pod template below.
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: user-service
      labels: 
        app: user-svc-dep # Ensure this matches the selector above.
    spec:
      containers:
        - name: user
          image: shaikkhajaibrahim/libuserssvc:1.0
          resources:
            requests:
              memory: 24M
              cpu: 100m
            limits:
              memory: 128M
              cpu: 500m
          env: 
            - name: SECRET_KEY
              value: 'YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k'
            - name: DATABASE_URL # Updated to use the correct database name.
              value: "postgresql://user:password@userdatabase-svc:5432/usersdb" # Corrected here.
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: NodePort
  selector:
    app: user-svc-dep     
  ports:
    - port: 80
      targetPort: 8000  
