--- 

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: users
  labels:
    app: users-svc-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: users-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  template:
    metadata:
      name: users
      labels: 
        app: users-svc
    spec:
      containers:
        - image: shaikkhajaibrahim/libuserssvc:1.0
          name: users-service
          resources:
            requests: 
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 250m
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@users-db:5432/usersdb"
            - name: SECRET_KEY
              value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
          ports:
            - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
spec:
  type: NodePort
  selector:
    app: users-svc
  ports:
    - port: 80
      targetPort: 8000
