---

apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: books-db-rs
  labels:
    app: books-db
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      db: books
  template:
    metadata:
      name: database
      labels:
        db: books
    spec:   
      containers:
        - name: database
          image: postgres:15-alpine
          env: 
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: booksdb
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 100Mi
              cpu: 250m
          ports:
            - containerPort: 5432


---
apiVersion: v1
kind: Service
metadata:
  name: books-db
spec:
  type: NodePort
  selector:
    db: books
  ports:
    - port: 5432
      targetPort: 5432