--- 

apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: user
  labels:
    app: user-svc-rs
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      name: user
      labels: 
        app: user-svc
    spec:
      containers:
        - image: shaikkhajaibrahim/libusersvc:1.0
          name: user-service
          resources:
            requests: 
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 250m
          env:
            - name: DATABASE_URL
              value: “postgresql://user:password@user-db:5432/userdb“
            - name: SECRET_KEY
              value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
          ports:
            - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
spec:
  type: NodePort
  selector:
    app: user-svc
  ports:
    - port: 80
      targetPort: 8000
