---

apiVersion: v1
kind: Pod
metadata:
  name: nginxwebserver
spec:
  containers:
    - name: webserver
      image: nginx:1.27
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d

