---

apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: spc-rs
  labels:
    app: spc
spec:
  minReadySeconds: 15
  replicas: 2
  selector:
    matchLabels: 
      env: dev
      app: spc
  template:
    metadata: 
      labels:
        app: spc
        env: dev
        version: v1.6.9
    spec:
      containers: 
        - name: spc
          image: shalaka136795/learning-test:2.0
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: 
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 500m