---

apiVersion: v1
kind: Pod
metadata:
  name: spc
  labels:
    env: dev
    app: spc
spec:
  containers:
    - name: spc
      image: sshaikkhajaibrahim/spcjan2024:1.0
      resources:
        limits: 
          cpu: 500m
          memory: 100M
        requests: 
          cpu: 250
          memory: 64M
      ports:
        - containerPort: 8080
          protocol: TCP