--- 

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: library
  labels:
    app: lib-svc-rs
  annotations: 
    kubernetes.io/change-cause: "version-1"
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: lib-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  template:
    metadata:
      name: library
      labels: 
        app: lib-svc
    spec:
      containers:
        - image: shaikkhajaibrahim/libwebstore:1.0
          name: lib-service
          resources:
            requests: 
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 250m
          startupProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            exec:
              command:
                - /bin/sh
                - -c
                - ps aux | grep node
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            tcpSocket: 
              port: 3000  
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: http://user-svc:8000/api/v1
            - name: REACT_APP_BOOKS_API_URL
              value: http://books-svc:8000/api/v1/books
            - name: REACT_APP_USERS_API_URL
              value: http://user-svc:8000/api/v1/users
          ports:
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: lib-svc
spec:
  type: NodePort
  selector:
    app: lib-svc
  ports:
    - port: 80
      targetPort: 3000
