---

apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  labels:
    type : secret
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dXNlcnNkYg==


---

apiVersion: v1
kind: Secret
metadata:
  name: books-db-secret
  labels:
    type : secret
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: Ym9va3NkYg==


---

apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  labels:
    type : secret
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAdXNlcnMtZGI6NTQzMi91c2Vyc2Ri
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==


---

apiVersion: v1
kind: Secret
metadata:
  name: books-secret
  labels:
    type : secret
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAYm9va3MtZGI6NTQzMi9ib29rc2Ri
  SECRET_KEY: WXRERVZXbkwzNWFBSVAtNXl4ZUxqQVo0OVI5MjAtbU1ORGZ3UHlXVUx1NjNIRnNZem8wZi1MTzJJbnhDOGV1NDI4aw==



