---


apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata: 
      labels:
        app: fluentd
    spec:
      template:  
        metadata:
          labels:
            app: fluentd          
        spec:
          containers:
            - name: tx-checker
              image: alpine
              args:
                - sleep
                - 1d
          restartPolicy: OnFailure


