---

- name: Install Tomcat Webserver from source code
  hosts: demo
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: download open jdk
      yum: name=java-11-openjdk state=present update_cache=yes

    - name: adding group
      group:
        name: tomcat
        state: present

    - name: adding user tomcat
      user: 
        name: tomcat
        create_home: yes
        shell: /bin/bash
        group: tomcat
        
    - name: creating directory
      file:
        path: /apps/opt/application/tomcat/
        state: directory
        owner: tomcat
        group: tomcat
        mode: "0755"

    - name: download zip file for tomcat
      get_url: url=https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.31/bin/apache-tomcat-10.1.31.tar.gz  dest=/apps/opt/application/tomcat/
               owner=tomcat group=tomcat   mode="0644"
    
    - name: unzip file
      unarchive: src=/apps/opt/application/tomcat/apache-tomcat-10.1.31.tar.gz  dest=/apps/opt/application/tomcat/
                 owner=tomcat group=tomcat remote_src=true  mode="0755"
                 
    - name: start tomcat service
      become_user: tomcat
      command: ./startup.sh
      args: 
        chdir: /apps/opt/application/tomcat/apache-tomcat-10.1.31/bin/

      
    - name: getting status
      shell: ps -ef | grep tomcat
      register: service_running

    - name: printing status
      debug:  
        var: service_running.stdout_lines

    


